//! What a new user ID inherits from the key it is bound to.
//!
//! Everything a certificate says about its own primary key — the key flags, the
//! expiry its owner set, the preferred algorithms, the features — lives in the
//! primary user ID's binding signature, with a direct-key signature as the
//! fallback. GnuPG writes no direct-key signature and claims no primary user
//! ID, so on a GnuPG key that binding is the only place those subpackets exist,
//! and the primary user ID is decided by whichever binding is newest. Binding a
//! new name with an empty signature therefore made the new name primary and
//! silently emptied the key: no certify flag, no sign flag, no expiry, no
//! preferences, in the store and in anything published from it.
//!
//! Keys generated by this app escape that, because `CertBuilder` marks their
//! first user ID primary, which is why the rest of the suite never saw it. The
//! fixture is a real GnuPG export instead, made with gpg 2.4.9 in a scratch
//! GNUPGHOME — real gpg output rather than something shaped by hand, because
//! the shape is the whole question:
//!
//! ```text
//! gpg --quick-gen-key 'Flags Fixture <flags@example.invalid>' default default 20y
//! gpg --armor --export-secret-keys "$FPR" > gnupg-flags-on-uid.asc
//! ```
//!
//! The key is DB9A673E983B3BE21EEC01F128828AA02DCF6FCF, generated for this test
//! alone and protected with the passphrase `fixture`. `default default` gives
//! the shape that matters: a `[SC]` primary whose user-ID binding carries key
//! flags 0x03, a twenty-year expiry, three preference lists and the features
//! octet, an `[E]` subkey, and no subpacket 25 and no 0x1F signature anywhere.
//! Twenty years so that the expiry under test outlives the test.
//!
//! Nothing here runs gpg. The fixture is bytes and the store is a tempdir.

use rpgp_core::{CertSummary, Store, lifecycle};
use sequoia_openpgp::Cert;
use sequoia_openpgp::cert::Preferences;
use sequoia_openpgp::packet::Signature;
use sequoia_openpgp::parse::Parse;
use sequoia_openpgp::policy::StandardPolicy;

const FIXTURE: &[u8] = include_bytes!("fixtures/gnupg-flags-on-uid.asc");
const PASSPHRASE: &str = "fixture";
const ORIGINAL: &str = "Flags Fixture <flags@example.invalid>";
const ADDED: &str = "Flags Fixture <work@example.invalid>";

fn scratch() -> (tempfile::TempDir, Store, String) {
    // Nothing here asks gpg-agent, and should a later change make something
    // do so, it must not be the developer's own; see `agent::AgentHome`.
    rpgp_core::agent::set_home(rpgp_core::agent::AgentHome::Nowhere);
    let dir = tempfile::tempdir().unwrap();
    let store = Store::open(dir.path().join("certs.d"), dir.path().join("secrets")).unwrap();
    let path = dir.path().join("fixture.asc");
    std::fs::write(&path, FIXTURE).unwrap();
    store.import_file(&path).unwrap();
    let fingerprint = Cert::from_bytes(FIXTURE).unwrap().fingerprint().to_hex();
    (dir, store, fingerprint)
}

/// Everything the key claims about itself, read the way the app reads it — and
/// only out of the certificate, so that the public half in cert-d answers it
/// exactly as the secret half does.
#[derive(Debug, PartialEq)]
struct Claims {
    primary_user_id: String,
    key_flags: Option<String>,
    expires: Option<std::time::SystemTime>,
    symmetric: Option<String>,
    features: Option<String>,
    can_certify: bool,
    can_sign: bool,
}

fn claims(cert: &Cert) -> Claims {
    let policy = StandardPolicy::new();
    let valid = cert.with_policy(&policy, None).unwrap();
    let summary = CertSummary::from_cert(cert);
    Claims {
        primary_user_id: String::from_utf8_lossy(valid.primary_userid().unwrap().userid().value())
            .into_owned(),
        key_flags: valid.primary_key().key_flags().map(|f| format!("{f:?}")),
        expires: valid.primary_key().key_expiration_time(),
        symmetric: valid
            .preferred_symmetric_algorithms()
            .map(|a| format!("{a:?}")),
        features: valid.features().map(|f| format!("{f:?}")),
        can_certify: summary.can_certify,
        can_sign: summary.can_sign,
    }
}

/// How many local secret keys the key flags offer for certifying and for
/// signing. The sign path picks its key by these flags, so a primary key that
/// has lost them answers zero there and signing falls through to a gpg-agent
/// that need not be running at all. certify() no longer asks them, since it
/// signs with the primary key whatever its flags say, but the certifier
/// picker's `can_certify` reads them, so a key that lost its certify flag
/// would drop out of the dialog.
fn local_keys(cert: &Cert) -> (usize, usize) {
    let policy = StandardPolicy::new();
    let valid = cert.with_policy(&policy, None).unwrap();
    (
        valid.keys().secret().for_certification().count(),
        valid.keys().secret().for_signing().count(),
    )
}

fn binding_of<'a>(cert: &'a Cert, user_id: &str) -> &'a Signature {
    let policy = StandardPolicy::new();
    cert.userids()
        .find(|ua| String::from_utf8_lossy(ua.userid().value()) == user_id)
        .unwrap_or_else(|| panic!("{user_id} is not on this key"))
        .binding_signature(&policy, None)
        .unwrap_or_else(|_| panic!("{user_id} has no binding the policy accepts"))
}

/// The premise. If this fails the fixture has been replaced and the tests below
/// prove nothing about GnuPG keys.
#[test]
fn the_fixture_keeps_the_keys_flags_and_expiry_on_its_user_id_binding() {
    let cert = Cert::from_bytes(FIXTURE).unwrap();
    let policy = StandardPolicy::new();

    let binding = binding_of(&cert, ORIGINAL);
    assert!(
        binding
            .key_flags()
            .is_some_and(|f| f.for_certification() && f.for_signing()),
        "the flags must be on the user-ID binding, which is where GnuPG puts them"
    );
    assert!(
        binding.key_validity_period().is_some(),
        "and so must the expiry"
    );
    assert!(
        binding.preferred_symmetric_algorithms().is_some() && binding.features().is_some(),
        "and the preferences and features"
    );
    assert_eq!(
        binding.primary_userid(),
        None,
        "GnuPG claims no primary user ID; that is what lets a newer binding take the title"
    );
    assert!(
        cert.with_policy(&policy, None)
            .unwrap()
            .direct_key_signature()
            .is_err(),
        "and it writes no direct-key signature to fall back on"
    );
}

/// The regression. Naming a key a second time must not change what the key
/// says about itself: it kept its certify and sign flags, its owner's expiry
/// and its preferences, and the identity everyone knows it by stayed primary.
///
/// Every field here failed before the new binding was templated from the
/// primary user ID's: the flags and the expiry read `None`, no local key
/// answered `for_certification` or `for_signing` — so certifying and signing
/// fell through to a gpg-agent that does not have to be there — and the details
/// pane named the brand-new address as the key's identity and its expiry as
/// never.
#[test]
fn adding_a_user_id_leaves_the_key_saying_what_it_said_before() {
    let (_dir, store, fingerprint) = scratch();
    let secret = store.secret_cert(&fingerprint).unwrap();
    let before = claims(&secret);
    assert_eq!(before.primary_user_id, ORIGINAL, "premise");
    assert!(before.can_certify && before.can_sign, "premise");
    assert!(before.expires.is_some(), "premise");
    assert_eq!(local_keys(&secret), (1, 1), "premise");

    let updated = lifecycle::add_user_id(&store, &fingerprint, ADDED, Some(PASSPHRASE)).unwrap();
    assert_eq!(claims(&updated), before);
    assert_eq!(local_keys(&updated), (1, 1));
    assert!(
        updated
            .userids()
            .any(|ua| String::from_utf8_lossy(ua.userid().value()) == ADDED),
        "the new name was still bound"
    );

    // And from the store, not merely from what the call handed back: the secret
    // half is what every later operation signs with, and the public half is what
    // the app reloads and what Publish would send.
    let secret = store.secret_cert(&fingerprint).unwrap();
    assert_eq!(claims(&secret), before);
    assert_eq!(local_keys(&secret), (1, 1));
    assert_eq!(claims(&store.lookup(&fingerprint).unwrap()), before);
}

/// The other half of copying the binding: the new identity has to be a real
/// identity of this key, carrying the same account of it as the one it was
/// copied from — RFC 9580 asks that every user ID repeat these subpackets,
/// because any one of them may be the one a stripped copy keeps. What it must
/// not carry is the claim to be primary, or the certificate would name two.
#[test]
fn the_added_user_id_carries_the_same_account_of_the_key_without_claiming_it() {
    let (_dir, store, fingerprint) = scratch();
    let updated = lifecycle::add_user_id(&store, &fingerprint, ADDED, Some(PASSPHRASE)).unwrap();

    let original = binding_of(&updated, ORIGINAL);
    let added = binding_of(&updated, ADDED);

    assert_eq!(added.key_flags(), original.key_flags());
    assert_eq!(
        added.key_validity_period(),
        original.key_validity_period(),
        "the expiry is relative to the key's creation, so copying it keeps the date its owner set"
    );
    assert_eq!(
        added.preferred_symmetric_algorithms(),
        original.preferred_symmetric_algorithms()
    );
    assert_eq!(
        added.preferred_hash_algorithms(),
        original.preferred_hash_algorithms()
    );
    assert_eq!(added.features(), original.features());

    assert_eq!(
        added.primary_userid(),
        None,
        "the new name must not claim the title"
    );
    assert_eq!(
        original.primary_userid(),
        Some(true),
        "and the identity that had it by default now says so, or the next name added moves it"
    );
}

/// Changing the expiry afterwards must still work on the repaired shape, and
/// leave it repaired. Sequoia builds its direct-key signature by copying the
/// primary user ID's binding, so a key emptied by the old `add_user_id` came
/// out of `set_expiry` with an empty direct-key signature as well — the damage
/// written a second time, in the one place that outlives every user ID.
#[test]
fn changing_the_expiry_after_an_added_user_id_keeps_the_flags() {
    let (_dir, store, fingerprint) = scratch();
    lifecycle::add_user_id(&store, &fingerprint, ADDED, Some(PASSPHRASE)).unwrap();
    let before = claims(&store.secret_cert(&fingerprint).unwrap());

    let year = std::time::Duration::from_secs(365 * 24 * 60 * 60);
    let updated =
        lifecycle::set_expiry(&store, &fingerprint, Some(year), Some(PASSPHRASE)).unwrap();
    let after = claims(&updated);

    assert_eq!(after.key_flags, before.key_flags);
    assert_eq!(after.primary_user_id, ORIGINAL);
    assert!(after.can_certify && after.can_sign);
    assert_ne!(after.expires, before.expires, "the expiry did move");
}
